services:
  node:
    image: node:22
    container_name: node_app
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "3000:3000"
    env_file:
      - .env

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mariadb:
    image: mariadb:10.8
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "tu_contraseña_segura"
      MYSQL_DATABASE: "travel_app"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "Blackwolf94"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
